# Generated by Django 5.1.4 on 2024-12-30 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pessoa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comentarios', to='minha_pessoa_app.blog'),
        ),
    ]
